### ISSUE TITLE
ERROR: Cannot execute provide-to-flash-loan

### ISSUE THREAD

**Issue by jahrek** [zk0821/TerraFlashLoanArbitrage#1]
Hi,
I compiled and uploaded contracts into Terra testnet. I have about 65 LUNA in my test account. When I'm trying to make a task "provide-to-flash-load" I'm getting error message.

Command:
`terrain task:run provide-to-flash-loan --network testnet`

Results:
```[...]
method: 'post',
      url: 'https://pisco-lcd.terra.dev/cosmos/tx/v1beta1/simulate',
      data: '{"tx_bytes":"XXXXXX"}'
    },
[...]
data: {
      code: 2,
      message: "rpc error: code = Unknown desc = failed to execute message; message index: 0: Generic error: Querier contract error: codespace: wasm, code: 8: execute wasm contract failed [CosmWasm/wasmd@v0.27.0/x/wasm/keeper/keeper.go:365] With gas wanted: '50000000' and gas used: '112678' : unknown request",
      details: []
    }
```

**Comment by zk0821** [comment]
Hello @jahrek ,

thank you for opening an issue. I have updated the repository with an English README.md.

Please follow the steps described there. If the issue still persists please let me know!

**Comment by zk0821** [comment]
No follow up for over 2 weeks. Closing for now.
